#!/usr/bin/python3
from subprocess import call, PIPE
import os
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('root_dir',type = str,nargs='?',default='', help='root directory (default = '')')
args = parser.parse_args()
cur_dir = os.path.dirname(os.path.abspath(__file__))
dirs = [
    '/etc/default/',
    '/etc/systemd/system',
    '/opt/cognitive/',
    '/etc/cognitive'
     ]

print(f'Current directory: {cur_dir}\nRoot directory:{args.root_dir}\nCreating directories...')

for dir in dirs:
    call(f'mkdir -p {args.root_dir}{dir}',shell = True)

call(f'rsync -r {cur_dir}/between_redis_and_ubx.py {args.root_dir}/opt/cognitive/', shell = True)
call(f'rsync -r {cur_dir}/gpsd {args.root_dir}/etc/default/', shell = True)
call(f'rsync -r {cur_dir}/redis_connection_gpsd.json {args.root_dir}/etc/cognitive/', shell = True)
call(f'rsync -r {cur_dir}/redis_fields_gpsd.json {args.root_dir}/etc/cognitive/', shell = True)
call(f'rsync -r {cur_dir}/gpsd.socket {args.root_dir}/etc/systemd/system/', shell = True)
call(f'rsync -r {cur_dir}/gps_handler_agro.service {args.root_dir}/etc/systemd/system/', shell = True)

#parser.add_argument(action=..., nargs=..., const=..., default=..., type=..., choices=..., required=..., help=..., metavar=..., dest=..., version=...)
